# -*- coding: utf-8 -*-
"""pdfplumber.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12dlD4sjQVv88HTWVaZ5Iev_VRGymBeKN
"""

pip install pdfplumber

#from google.colab import drive
from google.colab import files
#drive.mount("/content/drive")
#pdf = files.upload()

import pdfplumber
import pandas as pd

with pdfplumber.open("unclean_california_data.pdf") as pdf:
  first_page = pdf.pages[0]
  table = first_page.extract_table()
  df = pd.DataFrame(table[1:], columns=table[0])
  print(df)

im = pdf.pages[0].to_image(resolution=150)

im.debug_tablefinder(table_settings={})

df.to_csv("unclean_california_data.csv")
files.download("unclean_california_data.csv")

all_data = [] #empty list to append in each page's data later

with pdfplumber.open("unclean_california_data.pdf") as pdf:
  for page in pdf.pages:
    table = page.extract_table() #find the table in the page
    if table:
        df = pd.DataFrame(table[1:], columns=table[0])  #use 0 row as column names
        all_data.append(df)  # add data after each table found


if all_data:
    cleaned_data = pd.concat(all_data, ignore_index=True) # add all data together
    print(cleaned_data)
else:
    print("No tables found in the document.")

with pdfplumber.open("unclean_california_data.pdf") as pdf:
  for page in pdf.pages:
    print(page)

print(cleaned_data)

cleaned_data.to_csv("clean_california_data.csv")
files.download("clean_california_data.csv")